/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/jaycee/workspace/src/github/Nim/lib -o /home/jaycee/Android/projects/BristolTester/wifi_tools/nimcache/readSocket.o /home/jaycee/Android/projects/BristolTester/wifi_tools/nimcache/readSocket.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/socket.h>
#include <stdio.h>
#undef linux
typedef struct Socketimpl_aIhANOOoETolVz9cccNO9cRQ Socketimpl_aIhANOOoETolVz9cccNO9cRQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef NU8 Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 Socktype_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 Protocol_dqJ1OqRGclxIMMdSLRzzXg;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Filemode_fVUBHvW79bXUw1j55Oo9avSQ;
typedef NU8 Socketflag_4xio0cAXR7XG4pF9bVcpxEg_Set;
typedef NIM_CHAR TY_QQGLPNVVwLhYjkngqAxXQQ[4001];
struct  Socketimpl_aIhANOOoETolVz9cccNO9cRQ  {
int fd;
NIM_BOOL isbuffered;
union{
struct {TY_QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currpos;
NI buflen;
} S1;
} isbufferedU;
NI32 lasterror;
Domain_Q79bEtFARvq0ekDNtvj3Vqg domain;
Socktype_NQT1bItGG2X9byGdrWX7ujw socktype;
Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol;
};
N_NIMCALL(void, main_wzawqVgbvuCOq0asArd3rg)(void);
N_NIMCALL(Socketimpl_aIhANOOoETolVz9cccNO9cRQ*, newsocket_8Lrat9ciQTaGiwISp8ak13A)(Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0, Socktype_NQT1bItGG2X9byGdrWX7ujw socktype0, Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol0, NIM_BOOL buffered0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src0);
N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename0, Filemode_fVUBHvW79bXUw1j55Oo9avSQ mode0, NI bufsize0);
N_NIMCALL(NimStringDesc*, getfilename_vx2nCipg31BJ5d4PL8HgdA)(void);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
N_NIMCALL(void, bindaddr_1QV2AFuvaMgMWnPRPZq9bVw)(Socketimpl_aIhANOOoETolVz9cccNO9cRQ* socket0, NU16 port0, NimStringDesc* address0);
N_NIMCALL(void, listen_AOBVJUkpcJ1PzOE7Ql9b9ckQ)(Socketimpl_aIhANOOoETolVz9cccNO9cRQ* socket0, int backlog0);
N_NIMCALL(void, acceptaddr_BNPMZNX4vRbEgSo5HyvE5w)(Socketimpl_aIhANOOoETolVz9cccNO9cRQ* server0, Socketimpl_aIhANOOoETolVz9cccNO9cRQ** client0, NimStringDesc** address0, Socketflag_4xio0cAXR7XG4pF9bVcpxEg_Set flags0);
N_NIMCALL(NI, recv_hb6z1vAnNzXvhmRvLAv9byA)(Socketimpl_aIhANOOoETolVz9cccNO9cRQ* socket0, NimStringDesc** data0, NI size0, NI timeout0, Socketflag_4xio0cAXR7XG4pF9bVcpxEg_Set flags0);
N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f0, NimStringDesc* s0);
N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw)(FILE* f0);
static N_INLINE(void, initStackBottomWith)(void* locals0);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, readSocketDatInit000)(void);
STRING_LITERAL(T_WmtJyZBXNR4OIrkOwzO5cw_2, "", 0);
STRING_LITERAL(T_WmtJyZBXNR4OIrkOwzO5cw_3, " ", 1);
STRING_LITERAL(T_WmtJyZBXNR4OIrkOwzO5cw_4, "_", 1);
STRING_LITERAL(T_WmtJyZBXNR4OIrkOwzO5cw_5, ".csv", 4);
STRING_LITERAL(T_WmtJyZBXNR4OIrkOwzO5cw_6, "Connected from ", 15);
STRING_LITERAL(T_WmtJyZBXNR4OIrkOwzO5cw_7, "0", 1);
STRING_LITERAL(T_WmtJyZBXNR4OIrkOwzO5cw_8, "Wrote ", 6);

static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0) {
	void* LOC1;
	LOC1 = (void*)0;
	LOC1 = memcpy(dest0, source0, ((size_t) (size0)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	copymem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((void*) ((*src0).data)), ((NI) ((NI)((*src0).Sup.len + ((NI) 1)))));
	(*dest0).Sup.len += (*src0).Sup.len;
}

N_NIMCALL(NimStringDesc*, getfilename_vx2nCipg31BJ5d4PL8HgdA)(void) {
	NimStringDesc* result0;
	NimStringDesc* filename0;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
{	result0 = (NimStringDesc*)0;
	filename0 = ntgetDateStr();
	LOC1 = (NimStringDesc*)0;
	LOC2 = (NimStringDesc*)0;
	LOC2 = ntgetClockStr();
	LOC1 = rawNewString(filename0->Sup.len + LOC2->Sup.len + 1);
appendString(LOC1, filename0);
appendString(LOC1, ((NimStringDesc*) &T_WmtJyZBXNR4OIrkOwzO5cw_4));
appendString(LOC1, LOC2);
	filename0 = LOC1;
	LOC3 = (NimStringDesc*)0;
	LOC3 = rawNewString(filename0->Sup.len + 4);
appendString(LOC3, filename0);
appendString(LOC3, ((NimStringDesc*) &T_WmtJyZBXNR4OIrkOwzO5cw_5));
	result0 = LOC3;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, main_wzawqVgbvuCOq0asArd3rg)(void) {
	Socketimpl_aIhANOOoETolVz9cccNO9cRQ* socket0;
	Socketimpl_aIhANOOoETolVz9cccNO9cRQ* clientsocket0;
	NI readlinesuccess0;
	NimStringDesc* clientaddr0;
	NimStringDesc* readstring0;
	NimStringDesc* part0;
	FILE* file0;
	NimStringDesc* LOC1;
	socket0 = newsocket_8Lrat9ciQTaGiwISp8ak13A(((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2), ((Socktype_NQT1bItGG2X9byGdrWX7ujw) 1), ((Protocol_dqJ1OqRGclxIMMdSLRzzXg) 6), NIM_TRUE);
	clientsocket0 = newsocket_8Lrat9ciQTaGiwISp8ak13A(((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2), ((Socktype_NQT1bItGG2X9byGdrWX7ujw) 1), ((Protocol_dqJ1OqRGclxIMMdSLRzzXg) 6), NIM_TRUE);
	readlinesuccess0 = ((NI) 0);
	clientaddr0 = copyString(((NimStringDesc*) &T_WmtJyZBXNR4OIrkOwzO5cw_2));
	readstring0 = copyString(((NimStringDesc*) &T_WmtJyZBXNR4OIrkOwzO5cw_2));
	part0 = copyString(((NimStringDesc*) &T_WmtJyZBXNR4OIrkOwzO5cw_3));
	LOC1 = (NimStringDesc*)0;
	LOC1 = getfilename_vx2nCipg31BJ5d4PL8HgdA();
	file0 = open_hqzpWQbdA2B8l9a6wwNoP4g(LOC1, ((Filemode_fVUBHvW79bXUw1j55Oo9avSQ) 1), ((NI) -1));
	bindaddr_1QV2AFuvaMgMWnPRPZq9bVw(socket0, ((NU16) 6666), ((NimStringDesc*) &T_WmtJyZBXNR4OIrkOwzO5cw_2));
	listen_AOBVJUkpcJ1PzOE7Ql9b9ckQ(socket0, SOMAXCONN);
	{
		while (1) {
			acceptaddr_BNPMZNX4vRbEgSo5HyvE5w(socket0, &clientsocket0, (&clientaddr0), 2);
			printf("%s%s\012", ((NimStringDesc*) &T_WmtJyZBXNR4OIrkOwzO5cw_6)? (((NimStringDesc*) &T_WmtJyZBXNR4OIrkOwzO5cw_6))->data:"nil", clientaddr0? (clientaddr0)->data:"nil");
			fflush(stdout);
			readstring0 = copyString(((NimStringDesc*) &T_WmtJyZBXNR4OIrkOwzO5cw_2));
			part0 = copyString(((NimStringDesc*) &T_WmtJyZBXNR4OIrkOwzO5cw_7));
			{
				while (1) {
					NimStringDesc* LOC6;
					if (!!(((part0) && (part0)->Sup.len == 0))) goto LA5;
					readlinesuccess0 = recv_hb6z1vAnNzXvhmRvLAv9byA(clientsocket0, (&part0), ((NI) 1024), ((NI) -1), 2);
					LOC6 = (NimStringDesc*)0;
					LOC6 = rawNewString(readstring0->Sup.len + part0->Sup.len + 0);
appendString(LOC6, readstring0);
appendString(LOC6, part0);
					readstring0 = LOC6;
				} LA5: ;
			}
			write_c4mGyJBvK73pdM22jiweKQ(file0, readstring0);
			printf("%s%s\012", ((NimStringDesc*) &T_WmtJyZBXNR4OIrkOwzO5cw_8)? (((NimStringDesc*) &T_WmtJyZBXNR4OIrkOwzO5cw_8))->data:"nil", readstring0? (readstring0)->data:"nil");
			fflush(stdout);
		}
	}
	close_BWnr8V7RERYno9bIdPmw8Hw(file0);
}

static N_INLINE(void, initStackBottomWith)(void* locals0) {
	setStackBottom(locals0);
}
void PreMainInner() {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_nativesocketsDatInit000();
	stdlib_etcprivDatInit000();
	stdlib_hashesDatInit000();
	stdlib_setsDatInit000();
	stdlib_netDatInit000();
	stdlib_tablesDatInit000();
	stdlib_streamsDatInit000();
	stdlib_lexbaseDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_macrosDatInit000();
	stdlib_jsonDatInit000();
	readSocketDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_nativesocketsInit000();
	stdlib_etcprivInit000();
	stdlib_hashesInit000();
	stdlib_setsInit000();
	stdlib_netInit000();
	stdlib_tablesInit000();
	stdlib_streamsInit000();
	stdlib_lexbaseInit000();
	stdlib_unicodeInit000();
	stdlib_macrosInit000();
	stdlib_jsonInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	main_wzawqVgbvuCOq0asArd3rg();
}

NIM_EXTERNC N_NOINLINE(void, readSocketDatInit000)(void) {
}

