/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/jaycee/workspace/src/github/Nim/lib -o /home/jaycee/Android/projects/BristolTester/wifi_tools/nimcache/stdlib_nativesockets.o /home/jaycee/Android/projects/BristolTester/wifi_tools/nimcache/stdlib_nativesockets.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <string.h>
#include <sys/select.h>
#undef linux
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY_9apztJSmgERYU8fZOjI4pOg TY_9apztJSmgERYU8fZOjI4pOg;
typedef NU8 Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 Socktype_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 Protocol_dqJ1OqRGclxIMMdSLRzzXg;
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NIM_CHAR TY_dTlC27m9c9aWd5dvuePYanug[256];
struct TY_9apztJSmgERYU8fZOjI4pOg {
  TGenericSeq Sup;
  int data[SEQ_DECL_SIZE];
};
N_NIMCALL(int, toint_fU8QVvDL2nY9cu2Lt5eUZeQ)(Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0);
N_NIMCALL(int, toint_0zBaW59cZQJVrz1L13Wid5g)(Socktype_NQT1bItGG2X9byGdrWX7ujw typ0);
N_NIMCALL(int, toint_slGFLM9cFJ086GOC2tjJphw)(Protocol_dqJ1OqRGclxIMMdSLRzzXg p0);
N_NIMCALL(NimStringDesc*, HEX24_rzAI8EMyNBAQwGODeohhAA)(NU64 x0);
N_NOINLINE(void, raiseoserror_86HIIOlD5N61CWaO5GBgqA)(NI32 errorcode0, NimStringDesc* additionalinfo0);
N_NIMCALL(NI32, oslasterror_YyC2FKP9bqQiUDq2XVqW9acA)(void);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str0);
N_NIMCALL(struct timeval, timevalfrommilliseconds_X7JbWdPaNDQPHMVB9aPz9bkQ)(NI timeout0);
N_NIMCALL(void, createfdset_2WN0c6XLlKabdgianu73bg)(fd_set* fd0, TY_9apztJSmgERYU8fZOjI4pOg* s0, NI* m0);
N_NIMCALL(void, prunesocketset_1LwJOFdSmq6EdasZp5EGUA)(TY_9apztJSmgERYU8fZOjI4pOg** s0, fd_set* fd0);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq0, NI elemsize0, NI newlen0);
int osinvalidsocket_voz9aUXu8jtRbvGZZJHNE8w;
int nativeafinet_rQwsjQjVqXvdaL9aZofzWwg;
int nativeafinet6_Da6PongZL9aJxBrf7qeBmfA;
TNimType NTI_Q79bEtFARvq0ekDNtvj3Vqg;
TNimType NTI_NQT1bItGG2X9byGdrWX7ujw;
TNimType NTI_dqJ1OqRGclxIMMdSLRzzXg;

N_NIMCALL(int, toint_fU8QVvDL2nY9cu2Lt5eUZeQ)(Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0) {
	int result0;
	result0 = (int)0;
	switch (domain0) {
	case ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 0):
	{
		result0 = AF_UNIX;
	}
	break;
	case ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2):
	{
		result0 = AF_INET;
	}
	break;
	case ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23):
	{
		result0 = AF_INET6;
	}
	break;
	default:
	{
	}
	break;
	}
	return result0;
}

N_NIMCALL(int, toint_0zBaW59cZQJVrz1L13Wid5g)(Socktype_NQT1bItGG2X9byGdrWX7ujw typ0) {
	int result0;
	result0 = (int)0;
	switch (typ0) {
	case ((Socktype_NQT1bItGG2X9byGdrWX7ujw) 1):
	{
		result0 = SOCK_STREAM;
	}
	break;
	case ((Socktype_NQT1bItGG2X9byGdrWX7ujw) 2):
	{
		result0 = SOCK_DGRAM;
	}
	break;
	case ((Socktype_NQT1bItGG2X9byGdrWX7ujw) 5):
	{
		result0 = SOCK_SEQPACKET;
	}
	break;
	case ((Socktype_NQT1bItGG2X9byGdrWX7ujw) 3):
	{
		result0 = SOCK_RAW;
	}
	break;
	default:
	{
	}
	break;
	}
	return result0;
}

N_NIMCALL(int, toint_slGFLM9cFJ086GOC2tjJphw)(Protocol_dqJ1OqRGclxIMMdSLRzzXg p0) {
	int result0;
	result0 = (int)0;
	switch (p0) {
	case ((Protocol_dqJ1OqRGclxIMMdSLRzzXg) 6):
	{
		result0 = IPPROTO_TCP;
	}
	break;
	case ((Protocol_dqJ1OqRGclxIMMdSLRzzXg) 17):
	{
		result0 = IPPROTO_UDP;
	}
	break;
	case ((Protocol_dqJ1OqRGclxIMMdSLRzzXg) 18):
	{
		result0 = IPPROTO_IP;
	}
	break;
	case ((Protocol_dqJ1OqRGclxIMMdSLRzzXg) 19):
	{
		result0 = IPPROTO_IPV6;
	}
	break;
	case ((Protocol_dqJ1OqRGclxIMMdSLRzzXg) 20):
	{
		result0 = IPPROTO_RAW;
	}
	break;
	case ((Protocol_dqJ1OqRGclxIMMdSLRzzXg) 21):
	{
		result0 = IPPROTO_ICMP;
	}
	break;
	default:
	{
	}
	break;
	}
	return result0;
}

N_NIMCALL(int, newnativesocket_P59cS8yz3VHsnoN6zylI5Lg)(Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0, Socktype_NQT1bItGG2X9byGdrWX7ujw socktype0, Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol0) {
	int result0;
	int LOC1;
	int LOC2;
	int LOC3;
	result0 = (int)0;
	LOC1 = (int)0;
	LOC1 = toint_fU8QVvDL2nY9cu2Lt5eUZeQ(domain0);
	LOC2 = (int)0;
	LOC2 = toint_0zBaW59cZQJVrz1L13Wid5g(socktype0);
	LOC3 = (int)0;
	LOC3 = toint_slGFLM9cFJ086GOC2tjJphw(protocol0);
	result0 = socket(LOC1, LOC2, LOC3);
	return result0;
}

N_NIMCALL(NU16, ntohs_hTWZ9cGeQnQNEThS6k8qUKg)(NU16 x0) {
	NU16 result0;
	result0 = (NU16)0;
	result0 = (NU16)((NU16)((NU16)(x0) >> (NU16)(((NU16) 8))) | (NU16)((NU16)(x0) << (NU16)(((NU16) 8))));
	return result0;
}

N_NIMCALL(NU32, ntohl_RStKcIp64i7w9c4KBI2z46w)(NU32 x0) {
	NU32 result0;
	result0 = (NU32)0;
	result0 = (NU32)((NU32)((NU32)((NU32)((NU32)(x0) >> (NU32)(((NU32) 24))) | (NU32)((NU32)((NU32)(x0) >> (NU32)(((NU32) 8))) & ((NU32) 65280))) | (NU32)((NU32)((NU32)(x0) << (NU32)(((NU32) 8))) & ((NU32) 16711680))) | (NU32)((NU32)(x0) << (NU32)(((NU32) 24))));
	return result0;
}

N_NIMCALL(int, bindaddr_zpvqU0KQkzbkoKaehnMX2A)(int socket0, struct sockaddr* name0, socklen_t namelen0) {
	int result0;
	result0 = (int)0;
	result0 = bind(socket0, name0, namelen0);
	return result0;
}

N_NIMCALL(struct addrinfo*, getaddrinfo_fNPnGAYqSzdc2OjHEcTTAw)(NimStringDesc* address0, NU16 port0, Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0, Socktype_NQT1bItGG2X9byGdrWX7ujw socktype0, Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol0) {
	struct addrinfo* result0;
	struct addrinfo hints0;
	int gairesult0;
	NimStringDesc* LOC5;
	result0 = (struct addrinfo*)0;
	memset((void*)(&hints0), 0, sizeof(hints0));
	result0 = NIM_NIL;
	hints0.ai_family = toint_fU8QVvDL2nY9cu2Lt5eUZeQ(domain0);
	hints0.ai_socktype = toint_0zBaW59cZQJVrz1L13Wid5g(socktype0);
	hints0.ai_protocol = toint_slGFLM9cFJ086GOC2tjJphw(protocol0);
	{
		if (!(domain0 == ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23))) goto LA3;
		hints0.ai_flags = AI_V4MAPPED;
	}
	LA3: ;
	LOC5 = (NimStringDesc*)0;
	LOC5 = HEX24_rzAI8EMyNBAQwGODeohhAA(port0);
	gairesult0 = getaddrinfo(address0->data, LOC5->data, (&hints0), &result0);
	{
		NI32 LOC10;
		NCSTRING LOC11;
		NimStringDesc* LOC12;
		if (!!((gairesult0 == ((NI32) 0)))) goto LA8;
		LOC10 = (NI32)0;
		LOC10 = oslasterror_YyC2FKP9bqQiUDq2XVqW9acA();
		LOC11 = (NCSTRING)0;
		LOC11 = (char *)gai_strerror(gairesult0);
		LOC12 = (NimStringDesc*)0;
		LOC12 = cstrToNimstr(LOC11);
		raiseoserror_86HIIOlD5N61CWaO5GBgqA(LOC10, LOC12);
	}
	LA8: ;
	return result0;
}

N_NIMCALL(void, dealloc_o4AP9bp2a6Md29bi289aWTZew)(struct addrinfo* ai0) {
	freeaddrinfo(ai0);
}

N_NIMCALL(int, listen_BNAD35QpM7R1C7EJRtAZ3Q)(int socket0, int backlog0) {
	int result0;
	result0 = (int)0;
	result0 = listen(socket0, backlog0);
	return result0;
}

N_NIMCALL(struct timeval, timevalfrommilliseconds_X7JbWdPaNDQPHMVB9aPz9bkQ)(NI timeout0) {
	struct timeval result0;
	memset((void*)(&result0), 0, sizeof(result0));
	{
		NI seconds0;
		if (!!((timeout0 == ((NI) -1)))) goto LA3;
		seconds0 = (NI)(timeout0 / ((NI) 1000));
		result0.tv_sec = ((NI) (((NI32) (seconds0))));
		result0.tv_usec = ((NI) (((NI32) ((NI)((NI)(timeout0 - (NI)(seconds0 * ((NI) 1000))) * ((NI) 1000))))));
	}
	LA3: ;
	return result0;
}

N_NIMCALL(void, createfdset_2WN0c6XLlKabdgianu73bg)(fd_set* fd0, TY_9apztJSmgERYU8fZOjI4pOg* s0, NI* m0) {
	FD_ZERO(fd0);
	{
		int i_nWrf6GGpi6kMSu48P1sdpQ;
		NI i_nWrf6GGpi6kMSu48P1sdpQ_2;
		NI L_lAnPRRLtA1UXwDUiJslUqA;
		i_nWrf6GGpi6kMSu48P1sdpQ = (int)0;
		i_nWrf6GGpi6kMSu48P1sdpQ_2 = ((NI) 0);
		L_lAnPRRLtA1UXwDUiJslUqA = (s0 ? s0->Sup.len : 0);
		{
			while (1) {
				if (!(i_nWrf6GGpi6kMSu48P1sdpQ_2 < L_lAnPRRLtA1UXwDUiJslUqA)) goto LA3;
				i_nWrf6GGpi6kMSu48P1sdpQ = s0->data[i_nWrf6GGpi6kMSu48P1sdpQ_2];
				(*m0) = (((*m0) >= ((NI) (i_nWrf6GGpi6kMSu48P1sdpQ))) ? (*m0) : ((NI) (i_nWrf6GGpi6kMSu48P1sdpQ)));
				FD_SET(i_nWrf6GGpi6kMSu48P1sdpQ, fd0);
				i_nWrf6GGpi6kMSu48P1sdpQ_2 += ((NI) 1);
			} LA3: ;
		}
	}
}

N_NIMCALL(void, prunesocketset_1LwJOFdSmq6EdasZp5EGUA)(TY_9apztJSmgERYU8fZOjI4pOg** s0, fd_set* fd0) {
	NI i0;
	NI L0;
	i0 = ((NI) 0);
	L0 = ((*s0) ? (*s0)->Sup.len : 0);
	{
		while (1) {
			if (!(i0 < L0)) goto LA2;
			{
				int LOC5;
				LOC5 = (int)0;
				LOC5 = FD_ISSET((*s0)->data[i0], fd0);
				if (!(LOC5 == ((NI32) 0))) goto LA6;
				(*s0)->data[i0] = (*s0)->data[(NI)(L0 - ((NI) 1))];
				L0 -= ((NI) 1);
			}
			goto LA3;
			LA6: ;
			{
				i0 += ((NI) 1);
			}
			LA3: ;
		} LA2: ;
	}
	(*s0) = (TY_9apztJSmgERYU8fZOjI4pOg*) setLengthSeq(&((*s0))->Sup, sizeof(int), ((NI) (L0)));
}

N_NIMCALL(NI, select_f1UV2yno269c9cyjR0CwiQwg)(TY_9apztJSmgERYU8fZOjI4pOg** readfds0, NI timeout0) {
	NI result0;
	struct timeval tv0;
	fd_set rd0;
	NI m0;
	result0 = (NI)0;
	tv0 = timevalfrommilliseconds_X7JbWdPaNDQPHMVB9aPz9bkQ(timeout0);
	memset((void*)(&rd0), 0, sizeof(rd0));
	m0 = ((NI) 0);
	createfdset_2WN0c6XLlKabdgianu73bg((&rd0), (*readfds0), (&m0));
	{
		int LOC5;
		if (!!((timeout0 == ((NI) -1)))) goto LA3;
		LOC5 = (int)0;
		LOC5 = select(((int) ((NI)(m0 + ((NI) 1)))), (&rd0), NIM_NIL, NIM_NIL, (&tv0));
		result0 = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		int LOC7;
		LOC7 = (int)0;
		LOC7 = select(((int) ((NI)(m0 + ((NI) 1)))), (&rd0), NIM_NIL, NIM_NIL, NIM_NIL);
		result0 = ((NI) (LOC7));
	}
	LA1: ;
	prunesocketset_1LwJOFdSmq6EdasZp5EGUA(readfds0, (&rd0));
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void) {
	osinvalidsocket_voz9aUXu8jtRbvGZZJHNE8w = ((int) -1);
	nativeafinet_rQwsjQjVqXvdaL9aZofzWwg = AF_INET;
	nativeafinet6_Da6PongZL9aJxBrf7qeBmfA = AF_INET6;
}

NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void) {
static TNimNode* T_f9bP3LqjpgpB9cXL8Nnak7tQ_2[3];
NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_4;
static char* NIM_CONST T_f9bP3LqjpgpB9cXL8Nnak7tQ_3[3] = {
"AF_UNIX", 
"AF_INET", 
"AF_INET6"};
static TNimNode* T_f9bP3LqjpgpB9cXL8Nnak7tQ_5[4];
NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_7;
static char* NIM_CONST T_f9bP3LqjpgpB9cXL8Nnak7tQ_6[4] = {
"SOCK_STREAM", 
"SOCK_DGRAM", 
"SOCK_RAW", 
"SOCK_SEQPACKET"};
static TNimNode* T_f9bP3LqjpgpB9cXL8Nnak7tQ_8[6];
NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_10;
static char* NIM_CONST T_f9bP3LqjpgpB9cXL8Nnak7tQ_9[6] = {
"IPPROTO_TCP", 
"IPPROTO_UDP", 
"IPPROTO_IP", 
"IPPROTO_IPV6", 
"IPPROTO_RAW", 
"IPPROTO_ICMP"};
static TNimNode T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16];
NTI_Q79bEtFARvq0ekDNtvj3Vqg.size = sizeof(Domain_Q79bEtFARvq0ekDNtvj3Vqg);
NTI_Q79bEtFARvq0ekDNtvj3Vqg.kind = 14;
NTI_Q79bEtFARvq0ekDNtvj3Vqg.base = 0;
NTI_Q79bEtFARvq0ekDNtvj3Vqg.flags = 3;
for (T_f9bP3LqjpgpB9cXL8Nnak7tQ_4 = 0; T_f9bP3LqjpgpB9cXL8Nnak7tQ_4 < 3; T_f9bP3LqjpgpB9cXL8Nnak7tQ_4++) {
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_4+0].kind = 1;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_4+0].offset = T_f9bP3LqjpgpB9cXL8Nnak7tQ_4;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_4+0].name = T_f9bP3LqjpgpB9cXL8Nnak7tQ_3[T_f9bP3LqjpgpB9cXL8Nnak7tQ_4];
T_f9bP3LqjpgpB9cXL8Nnak7tQ_2[T_f9bP3LqjpgpB9cXL8Nnak7tQ_4] = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_4+0];
}
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[0].offset = 0;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[1].offset = 2;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[2].offset = 23;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3].len = 3; T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3].kind = 2; T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3].sons = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_2[0];
NTI_Q79bEtFARvq0ekDNtvj3Vqg.node = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3];
NTI_Q79bEtFARvq0ekDNtvj3Vqg.flags = 1<<2;
NTI_NQT1bItGG2X9byGdrWX7ujw.size = sizeof(Socktype_NQT1bItGG2X9byGdrWX7ujw);
NTI_NQT1bItGG2X9byGdrWX7ujw.kind = 14;
NTI_NQT1bItGG2X9byGdrWX7ujw.base = 0;
NTI_NQT1bItGG2X9byGdrWX7ujw.flags = 3;
for (T_f9bP3LqjpgpB9cXL8Nnak7tQ_7 = 0; T_f9bP3LqjpgpB9cXL8Nnak7tQ_7 < 4; T_f9bP3LqjpgpB9cXL8Nnak7tQ_7++) {
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_7+4].kind = 1;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_7+4].offset = T_f9bP3LqjpgpB9cXL8Nnak7tQ_7;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_7+4].name = T_f9bP3LqjpgpB9cXL8Nnak7tQ_6[T_f9bP3LqjpgpB9cXL8Nnak7tQ_7];
T_f9bP3LqjpgpB9cXL8Nnak7tQ_5[T_f9bP3LqjpgpB9cXL8Nnak7tQ_7] = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_7+4];
}
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].offset = 1;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[5].offset = 2;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[6].offset = 3;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[7].offset = 5;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8].len = 4; T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8].kind = 2; T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8].sons = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_5[0];
NTI_NQT1bItGG2X9byGdrWX7ujw.node = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8];
NTI_NQT1bItGG2X9byGdrWX7ujw.flags = 1<<2;
NTI_dqJ1OqRGclxIMMdSLRzzXg.size = sizeof(Protocol_dqJ1OqRGclxIMMdSLRzzXg);
NTI_dqJ1OqRGclxIMMdSLRzzXg.kind = 14;
NTI_dqJ1OqRGclxIMMdSLRzzXg.base = 0;
NTI_dqJ1OqRGclxIMMdSLRzzXg.flags = 3;
for (T_f9bP3LqjpgpB9cXL8Nnak7tQ_10 = 0; T_f9bP3LqjpgpB9cXL8Nnak7tQ_10 < 6; T_f9bP3LqjpgpB9cXL8Nnak7tQ_10++) {
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_10+9].kind = 1;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_10+9].offset = T_f9bP3LqjpgpB9cXL8Nnak7tQ_10;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_10+9].name = T_f9bP3LqjpgpB9cXL8Nnak7tQ_9[T_f9bP3LqjpgpB9cXL8Nnak7tQ_10];
T_f9bP3LqjpgpB9cXL8Nnak7tQ_8[T_f9bP3LqjpgpB9cXL8Nnak7tQ_10] = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_10+9];
}
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9].offset = 6;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[10].offset = 17;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[11].offset = 18;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[12].offset = 19;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[13].offset = 20;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[14].offset = 21;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15].len = 6; T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15].kind = 2; T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15].sons = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8[0];
NTI_dqJ1OqRGclxIMMdSLRzzXg.node = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15];
NTI_dqJ1OqRGclxIMMdSLRzzXg.flags = 1<<2;
}

