/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/jaycee/workspace/src/github/Nim/lib -o /home/jaycee/Android/projects/BristolTester/wifi_tools/nimcache/stdlib_parseutils.o /home/jaycee/Android/projects/BristolTester/wifi_tools/nimcache/stdlib_parseutils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef linux
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void) {
}

